package com.careeros.domain;

public final class DomainEnums {
    private DomainEnums() {}

    public enum EventType { PUBLIC_INSTITUTION, STATE_OWNED_ENTERPRISE, UNIVERSITY, HOSPITAL, GOVERNMENT_PURCHASED_SERVICE, OTHER }
    public enum OrganizationType { GOVERNMENT, PUBLIC_INSTITUTION, STATE_OWNED_ENTERPRISE, UNIVERSITY, HOSPITAL, RESEARCH_INSTITUTE, OTHER, UNKNOWN }
    public enum EmploymentType { ESTABLISHMENT, PERSONNEL_AGENCY, LABOR_DISPATCH, CONTRACT, PROJECT_BASED, UNKNOWN }
    public enum JobFamily { SOFTWARE, DATA, AI, CYBERSECURITY, INFORMATION_SYSTEMS, DIGITALIZATION, IT_OPERATIONS, RESEARCH, PRODUCT, OTHER }
    public enum EducationLevel { UNKNOWN, HIGH_SCHOOL, ASSOCIATE, BACHELOR, MASTER, DOCTORATE }
    public enum RuleType { AGE, EDUCATION, EXACT_MAJOR, GRADUATE_YEAR, EXPERIENCE, PROFESSIONAL_TITLE, OTHER }
    public enum EligibilityStatus { ELIGIBLE, LIKELY_ELIGIBLE, UNCERTAIN, LIKELY_INELIGIBLE, INELIGIBLE }
    public enum EvidenceType { OFFICIAL_NOTICE, OFFICIAL_ATTACHMENT, ORGANIZATION_PAGE, POLICY, MANUAL_NOTE }
    public enum OpportunityStatus { NEW, REVIEWING, SHORTLISTED, APPLIED, CLOSED, REJECTED, ARCHIVED }
    public enum ExtractionSourceType { HTML, PDF }
    public enum DataQualityStatus { RAW, PARSED, NORMALIZED, REVIEW_REQUIRED, VERIFIED, REJECTED, FAILED }
    public enum TargetScopeStatus { INCLUDED, EXCLUDED, NEEDS_REVIEW }
    public enum JobAdmissionReason {
        LEGACY_UNVERIFIED, NOT_CLASSIFIED, CONTENT_CHANGED, TARGET_TECHNICAL_ROLE,
        DOCTOR_REQUIRED, TEACHING_ROLE, POSTDOCTORAL_ROLE, ADMINISTRATIVE_ROLE,
        SALES_ROLE, LABOR_DISPATCH, PROJECT_BASED, INTERNSHIP,
        NON_TECHNICAL_ROLE, AMBIGUOUS_DUTIES, EMPLOYMENT_IDENTITY_UNKNOWN
    }
    public enum ParserQuality { ACCEPTABLE, LOW_TEXT_QUALITY }
    public enum FactStatus { EXPLICIT, INTERPRETED, UNKNOWN }
    public enum ReviewStatus { PENDING, RESOLVED }
    public enum ReviewDecision { CONFIRM, CORRECT, REJECT, NEED_MORE_EVIDENCE }
    public enum ReviewReasonCode {
        LOW_CONFIDENCE, MISSING_EVIDENCE, ORGANIZATION_TYPE_UNKNOWN,
        CONFLICTING_SOURCES, PARSER_FAILURE, LOW_TEXT_QUALITY,
        SCHEMA_INVALID, RESTRICTIVE_FACT_FROM_LLM
    }
    public enum LocatorType { HTML, PDF }
    public enum AssessmentFactStatus { EXPLICIT, INTERPRETED, UNKNOWN }
    public enum AssessmentDimensionType {
        MAJOR_FIT, SKILL_FIT, EXPERIENCE_FIT, RESEARCH_FIT, PROFESSIONAL_TITLE_FIT, PREFERENCE_FIT,
        EMPLOYMENT_SECURITY, FUNDING_STABILITY, ORGANIZATION_STABILITY, POLICY_STABILITY,
        BUSINESS_VOLATILITY, LAYOFF_RISK, CONTRACT_RISK
    }
    public enum OpportunityTier { T1, T2, T3, EXCLUDED }
    public enum RecommendationStatus { RECOMMENDED, REVIEW, NOT_RECOMMENDED, EXCLUDED }
}
