package com.careeros.domain;

public final class DomainEnums {
    private DomainEnums() {}

    public enum EventType { PUBLIC_INSTITUTION, STATE_OWNED_ENTERPRISE, UNIVERSITY, HOSPITAL, GOVERNMENT_PURCHASED_SERVICE, OTHER }
    public enum OrganizationType { GOVERNMENT, PUBLIC_INSTITUTION, STATE_OWNED_ENTERPRISE, UNIVERSITY, HOSPITAL, RESEARCH_INSTITUTE, OTHER, UNKNOWN }
    /**
     * 产品需求 §5：事业编、员额/报备员额、校聘、国企正式、合同制/编外、劳务派遣、未知必须能分开表达。
     * PROJECT_BASED（项目聘用）保留，§3 把它列入默认排除。
     */
    public enum EmploymentType {
        ESTABLISHMENT, AUTHORIZED_HEADCOUNT, SCHOOL_HIRED, STATE_OWNED_REGULAR,
        PERSONNEL_AGENCY, LABOR_DISPATCH, CONTRACT, PROJECT_BASED, UNKNOWN
    }
    public enum JobFamily { SOFTWARE, DATA, AI, CYBERSECURITY, INFORMATION_SYSTEMS, DIGITALIZATION, IT_OPERATIONS, RESEARCH, PRODUCT, OTHER }
    public enum EducationLevel { UNKNOWN, HIGH_SCHOOL, ASSOCIATE, BACHELOR, MASTER, DOCTORATE }
    public enum RuleType { AGE, EDUCATION, DEGREE, EXACT_MAJOR, GRADUATE_YEAR, EXPERIENCE, PROFESSIONAL_TITLE, POLITICAL_STATUS, APPLICANT_TYPE, OTHER_CONDITIONS, OTHER }
    /** 产品需求 §6.1：资格是硬判定，不是分数。禁止引入 LIKELY_* 之类的程度值。 */
    public enum EligibilityStatus { ELIGIBLE, INELIGIBLE, CONDITIONAL, NEEDS_CONFIRMATION, CONFLICTING_EVIDENCE }
    public enum CriterionStatus { PASS, FAIL, CONDITIONAL, UNKNOWN, NOT_APPLICABLE }
    /** 产品需求 §3：不同用工性质必须分池，不能只给一个"半体制"标签。 */
    public enum OpportunityTier { T1_ESTABLISHMENT_TARGET, T2_IDENTITY_REVIEW, T3_STABLE_SOE_BACKUP, EXCLUDED, UNKNOWN }
    public enum EvidenceType { OFFICIAL_NOTICE, OFFICIAL_ATTACHMENT, ORGANIZATION_PAGE, POLICY, MANUAL_NOTE }
    public enum OpportunityStatus { NEW, REVIEWING, SHORTLISTED, APPLIED, CLOSED, REJECTED, ARCHIVED }
    public enum ExtractionSourceType { HTML, PDF }
    public enum DataQualityStatus { RAW, PARSED, NORMALIZED, REVIEW_REQUIRED, VERIFIED, REJECTED, FAILED }
    public enum ParserQuality { ACCEPTABLE, LOW_TEXT_QUALITY }
    public enum FactStatus { EXPLICIT, INTERPRETED, UNKNOWN }
    public enum ReviewStatus { PENDING, RESOLVED }
    public enum ReviewDecision { CONFIRM, CORRECT, REJECT, NEED_MORE_EVIDENCE }
    public enum ReviewReasonCode {
        LOW_CONFIDENCE, MISSING_EVIDENCE, ORGANIZATION_TYPE_UNKNOWN,
        CONFLICTING_SOURCES, PARSER_FAILURE, LOW_TEXT_QUALITY,
        SCHEMA_INVALID, RESTRICTIVE_FACT_FROM_LLM
    }
    public enum LocatorType { HTML, PDF }
}
