package com.careeros.domain;

public final class DomainEnums {
    private DomainEnums() {}

    public enum EventType { PUBLIC_INSTITUTION, STATE_OWNED_ENTERPRISE, UNIVERSITY, HOSPITAL, GOVERNMENT_PURCHASED_SERVICE, OTHER }
    public enum OrganizationType { GOVERNMENT, PUBLIC_INSTITUTION, STATE_OWNED_ENTERPRISE, UNIVERSITY, HOSPITAL, RESEARCH_INSTITUTE, OTHER, UNKNOWN }
    public enum EmploymentType { ESTABLISHMENT, PERSONNEL_AGENCY, LABOR_DISPATCH, CONTRACT, PROJECT_BASED, UNKNOWN }
    public enum JobFamily { SOFTWARE, DATA, AI, CYBERSECURITY, INFORMATION_SYSTEMS, DIGITALIZATION, IT_OPERATIONS, RESEARCH, PRODUCT, OTHER }
    public enum EducationLevel { UNKNOWN, HIGH_SCHOOL, ASSOCIATE, BACHELOR, MASTER, DOCTORATE }
    public enum RuleType { AGE, EDUCATION, EXACT_MAJOR, GRADUATE_YEAR, EXPERIENCE, PROFESSIONAL_TITLE, OTHER }
    public enum EligibilityStatus { ELIGIBLE, LIKELY_ELIGIBLE, UNCERTAIN, LIKELY_INELIGIBLE, INELIGIBLE }
    public enum EvidenceType { OFFICIAL_NOTICE, OFFICIAL_ATTACHMENT, ORGANIZATION_PAGE, POLICY, MANUAL_NOTE }
    public enum OpportunityStatus { NEW, REVIEWING, SHORTLISTED, APPLIED, CLOSED, REJECTED, ARCHIVED }
    public enum ExtractionSourceType { HTML, PDF }
    public enum DataQualityStatus { RAW, PARSED, NORMALIZED, REVIEW_REQUIRED, VERIFIED, REJECTED, FAILED }
    public enum ParserQuality { ACCEPTABLE, LOW_TEXT_QUALITY }
    public enum FactStatus { EXPLICIT, INTERPRETED, UNKNOWN }
    public enum ReviewStatus { PENDING, RESOLVED }
    public enum ReviewDecision { CONFIRM, CORRECT, REJECT, NEED_MORE_EVIDENCE }
    public enum ReviewReasonCode {
        LOW_CONFIDENCE, MISSING_EVIDENCE, ORGANIZATION_TYPE_UNKNOWN,
        CONFLICTING_SOURCES, PARSER_FAILURE, LOW_TEXT_QUALITY,
        SCHEMA_INVALID, RESTRICTIVE_FACT_FROM_LLM
    }
    public enum LocatorType { HTML, PDF }
}
